data:
  container_name: data
  build: data

tile_db:
  container_name: tile_db
  build: tile_db
  command: true

variant_store:
  container_name: variant_store
  build: variant_store
  volumes_from:
    - data
  ports:
    - 5000
