
version: '2'

services:
  variant_metadb:
    container_name: variant_metadb
    build: variant_metadb
    ports:
    - 5432:5432

  variant_metadb_init:
    container_name: variant_metadb_init
    build: variant_metadb_init
    links:
    - variant_metadb
    restart: on-failure

  variant_store:
    container_name: variant_store
    build: variant_store
    ports:
    - 6000:5000