variant_store_data:

  container_name: variant_store_data
  build: data

tile_db:
  container_name: tile_db
  build: tile_db
  command: /bin/true

variant_store:
  container_name: variant_store
  build: variant_store
  volumes_from:
    - variant_store_data
  ports:
    - 6000:5000
